bus:
  city_code: '25'
  key: 3d3d725df7c8daa3445ada3ceb7778d94328541e6eb616f02c0b82cb11ff182f
  node_id: '40190'
frame:
  calendars:
  - color: '#fff04d'
    url: https://calendar.google.com/calendar/ical/bob.gondrae%40gmail.com/private-00822d9dbbe3140b9253bf2e0bda95c6/basic.ics
  ical_url: https://calendar.google.com/calendar/ical/bob.gondrae%40gmail.com/private-00822d9dbbe3140b9253bf2e0bda95c6/basic.ics
  tz: Asia/Seoul
home_assistant:
  base_url: http://ttms03.duckdns.org:8123
  include_domains:
  - light
  - switch
  include_entities: []
  timeout: 10
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJlNDAwNzg0ZWVjZmE0NzI0YmMyOTBlNzg2ODc4YjgyMyIsImlhdCI6MTc2MzAzOTgxNSwiZXhwIjoyMDc4Mzk5ODE1fQ.6pYqokebv0rzO3IcCXnSuIkS140oZgrP0QdjRc6N5II
photos:
  album: default
server:
  port: 5320
telegram:
  allowed_user_ids:
  - 5517670242
  bot_token: 8279263607:AAEzHxlSYMfsXwP7OpXWw5NB40VTCDfBlJw
  mode: polling
  path_secret: ''
  webhook_base: ''
todoist:
  api_token: 0aa4d2a4f95e952a1f635c14d6c6ba7e3b26bc2b
  project_id: ''
weather:
  api_key: 9809664c22a3501382380f2781e1a9da
  location: Seoul, South Korea
  provider: openweathermap
  units: metric

#aabd743b-b1f4-40bc-89a8-fddf5e655771 (samsung)
